import { useState } from 'react'
import { useTax } from '../context/useTax'
import { calculateIncomeTax } from '../utils/taxCalculator'
import '../styles/pages.css'

function formatAUD(n) {
  return n.toLocaleString('en-AU', { style: 'currency', currency: 'AUD', minimumFractionDigits: 0, maximumFractionDigits: 0 })
}

function padLabel(label, width) {
  return label.padEnd(width, ' ')
}

export default function Lodgement() {
  const { cgtResult, deductionItems, payslips, otherIncome } = useTax()
  const [copied, setCopied] = useState(false)

  // Income
  const employmentGross = payslips.reduce((s, p) => s + p.grossEarnings, 0)
  const otherGross = otherIncome.reduce((s, o) => s + o.amount, 0)
  const totalGross = employmentGross + otherGross
  const totalTaxWithheld = payslips.reduce((s, p) => s + p.taxWithheld, 0)
    + otherIncome.reduce((s, o) => s + (o.taxWithheld || 0), 0)

  // Deductions
  const approvedDeductions = deductionItems.filter(d => d.status === 'approved')
  const totalDeductions = approvedDeductions.reduce((s, d) => s + d.amountAUD, 0)

  // CGT
  const netCGT = cgtResult?.summary?.netCGT ?? 0

  // Taxable income
  const taxableIncome = Math.max(0, totalGross - totalDeductions)

  // Tax calculation
  const { netTax } = totalGross > 0 ? calculateIncomeTax(taxableIncome) : { netTax: 0 }
  const totalTaxPayable = netTax + Math.max(0, netCGT) // add positive CGT to tax payable
  const estimatedRefund = totalTaxWithheld - totalTaxPayable
  const isRefund = estimatedRefund >= 0

  const hasData = totalGross > 0

  // Checklist
  const checklist = [
    { label: 'Crypto CGT calculated', done: !!cgtResult && cgtResult.summary.eventCount > 0 },
    { label: 'Deductions reviewed', done: deductionItems.length > 0 && deductionItems.filter(d => d.status === 'pending').length === 0 },
    { label: 'Income entered', done: payslips.length > 0 || otherIncome.length > 0 },
    { label: 'PAYG data available', done: totalTaxWithheld > 0 },
    { label: 'No pending deductions', done: deductionItems.filter(d => d.status === 'pending').length === 0 },
  ]
  const allDone = checklist.every(c => c.done)

  // Deductions by category
  const deductionsByCategory = approvedDeductions.reduce((acc, d) => {
    const key = d.category?.label ?? 'Uncategorised'
    if (!acc[key]) acc[key] = { count: 0, total: 0 }
    acc[key].count++
    acc[key].total += d.amountAUD
    return acc
  }, {})

  // Copy to clipboard
  function handleCopy() {
    const W = 22
    const lines = [
      'TaxMate AU — FY 2024-25 Return Summary',
      '=======================================',
      `${padLabel('Employment Income:', W)} ${formatAUD(employmentGross)}`,
      `${padLabel('Other Income:', W)} ${formatAUD(otherGross)}`,
      `${padLabel('Total Gross:', W)} ${formatAUD(totalGross)}`,
      `${padLabel('Less Deductions:', W)} -${formatAUD(totalDeductions)}`,
      `${padLabel('Taxable Income:', W)} ${formatAUD(taxableIncome)}`,
      `${padLabel('Income Tax Payable:', W)} ${formatAUD(netTax)}`,
      `${padLabel('CGT Liability:', W)} ${formatAUD(Math.max(0, netCGT))}`,
      `${padLabel('Total Tax Payable:', W)} ${formatAUD(totalTaxPayable)}`,
      `${padLabel('Tax Withheld:', W)} -${formatAUD(totalTaxWithheld)}`,
      '-------------------------------',
      isRefund
        ? `${padLabel('Estimated Refund:', W)} ${formatAUD(Math.abs(estimatedRefund))}`
        : `${padLabel('Estimated Liability:', W)} ${formatAUD(Math.abs(estimatedRefund))}`,
      '',
      'Generated by TaxMate AU — estimate only',
    ]
    navigator.clipboard.writeText(lines.join('\n')).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  return (
    <div className="page-container">
      <div className="page-header">
        <h1>Lodgement Prep</h1>
        <p>Review your complete return summary and export it for your accountant or myGov lodgement.</p>
      </div>

      {/* Estimated refund hero */}
      <div className="lodge-refund-hero">
        <div className="lodge-refund-label">
          {hasData ? (isRefund ? 'Estimated Refund' : 'Estimated Liability') : 'Estimated Refund / Liability'}
        </div>
        {hasData ? (
          <>
            <div
              className={`payg-result-value${isRefund ? ' payg-result-value--refund' : ' payg-result-value--liability'}`}
              style={{ fontFamily: 'var(--font-heading)', fontSize: '42px', lineHeight: 1, marginBottom: 10 }}
            >
              {formatAUD(Math.abs(estimatedRefund))}
            </div>
            <p className="refund-hero-sub">
              Estimate only — does not include Medicare levy, private health offset, or other adjustments
            </p>
          </>
        ) : (
          <div className="lodge-refund-value">Complete all modules to calculate your estimate</div>
        )}
      </div>

      <hr className="divider" />

      {/* Return summary table */}
      <div className="section-heading">
        <h2>Return Summary</h2>
        <span className="section-sub">FY 2024–25</span>
      </div>

      <table className="summary-table" style={{ marginBottom: 28 }}>
        <thead>
          <tr>
            <th>Item</th>
            <th style={{ textAlign: 'right' }}>Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Employment Income</td>
            <td style={{ textAlign: 'right' }}>{formatAUD(employmentGross)}</td>
          </tr>
          <tr>
            <td>Other Income</td>
            <td style={{ textAlign: 'right' }}>{formatAUD(otherGross)}</td>
          </tr>
          <tr>
            <td style={{ fontWeight: 600, color: 'var(--text-primary)' }}>Total Gross Income</td>
            <td style={{ textAlign: 'right', fontWeight: 600, color: 'var(--accent)' }}>{formatAUD(totalGross)}</td>
          </tr>
          <tr>
            <td style={{ color: '#6fcf97' }}>Less: Approved Deductions</td>
            <td style={{ textAlign: 'right', color: '#6fcf97' }}>
              {totalDeductions > 0 ? `-${formatAUD(totalDeductions)}` : formatAUD(0)}
            </td>
          </tr>
          <tr>
            <td style={{ fontWeight: 600, color: 'var(--text-primary)' }}>Taxable Income</td>
            <td style={{ textAlign: 'right', fontWeight: 600, color: 'var(--text-primary)' }}>{formatAUD(taxableIncome)}</td>
          </tr>
          <tr>
            <td>Income Tax Payable</td>
            <td style={{ textAlign: 'right' }}>{formatAUD(netTax)}</td>
          </tr>
          <tr>
            <td style={{ color: netCGT > 0 ? '#f0a040' : 'var(--text-secondary)' }}>
              CGT Liability {netCGT <= 0 && netCGT !== 0 ? '(loss — not added)' : ''}
            </td>
            <td style={{ textAlign: 'right', color: netCGT > 0 ? '#f0a040' : 'var(--text-secondary)' }}>
              {formatAUD(Math.max(0, netCGT))}
            </td>
          </tr>
          <tr>
            <td style={{ fontWeight: 600, color: 'var(--text-primary)' }}>Total Tax Payable</td>
            <td style={{ textAlign: 'right', fontWeight: 600, color: 'var(--text-primary)' }}>{formatAUD(totalTaxPayable)}</td>
          </tr>
          <tr>
            <td style={{ color: '#6fcf97' }}>Less: Tax Withheld (PAYG)</td>
            <td style={{ textAlign: 'right', color: '#6fcf97' }}>
              {totalTaxWithheld > 0 ? `-${formatAUD(totalTaxWithheld)}` : formatAUD(0)}
            </td>
          </tr>
          <tr className="total-row">
            <td>
              <strong>{isRefund ? 'Estimated Refund' : 'Estimated Liability'}</strong>
            </td>
            <td style={{ textAlign: 'right' }}>
              <strong
                className={isRefund ? 'payg-result-value--refund' : 'payg-result-value--liability'}
                style={{ fontFamily: 'var(--font-heading)', fontSize: '20px' }}
              >
                {formatAUD(Math.abs(estimatedRefund))}
              </strong>
            </td>
          </tr>
        </tbody>
      </table>

      {/* Deductions breakdown */}
      {approvedDeductions.length > 0 && (
        <>
          <div className="section-heading">
            <h2>Approved Deductions</h2>
            <span className="section-sub">{approvedDeductions.length} items · {formatAUD(totalDeductions)} total</span>
          </div>
          <div style={{ marginBottom: 28, display: 'flex', flexDirection: 'column', gap: 8 }}>
            {Object.entries(deductionsByCategory).map(([cat, { count, total }]) => (
              <div key={cat} style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                padding: '10px 14px',
                background: 'var(--bg-surface)',
                border: '1px solid var(--border)',
                borderRadius: 'var(--radius-md)',
                fontSize: 13.5,
              }}>
                <span style={{ color: 'var(--text-secondary)' }}>{cat}</span>
                <span style={{ color: 'var(--text-muted)', fontSize: 12, marginLeft: 12 }}>{count} item{count !== 1 ? 's' : ''}</span>
                <span style={{ color: '#6fcf97', fontFamily: 'var(--font-heading)', fontSize: 16, marginLeft: 'auto' }}>
                  {formatAUD(total)}
                </span>
              </div>
            ))}
          </div>
        </>
      )}

      <hr className="divider" />

      {/* Pre-lodgement checklist */}
      <div className="section-heading">
        <h2>Pre-lodgement checklist</h2>
        <span className="section-sub">
          {allDone ? 'All items complete' : `${checklist.filter(c => c.done).length} of ${checklist.length} complete`}
        </span>
      </div>

      <div className="checklist">
        {checklist.map((item) => (
          <div className="checklist-item" key={item.label}>
            <span className={`check-box${item.done ? ' check-box--done' : ''}`}>
              {item.done && (
                <svg width="10" height="10" viewBox="0 0 10 10" fill="none">
                  <path d="M2 5l2.5 2.5L8 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              )}
            </span>
            <span className="checklist-label">{item.label}</span>
          </div>
        ))}
      </div>

      <hr className="divider" />

      {/* Export section */}
      <div className="section-heading">
        <h2>Export options</h2>
        <span className="section-sub">Export your return summary</span>
      </div>

      <div className="export-grid">
        <div className="export-card">
          <div className="placeholder-card-title">Export PDF Summary</div>
          <p className="placeholder-card-desc">Full summary formatted for your accountant or tax agent.</p>
          <button
            className="export-btn"
            disabled
            title="Coming soon"
            style={{ marginTop: 12 }}
          >
            Export PDF
          </button>
        </div>
        <div className="export-card">
          <div className="placeholder-card-title">Copy to Clipboard</div>
          <p className="placeholder-card-desc">Copy a plain-text version of your return summary to the clipboard.</p>
          <button
            className="export-btn"
            onClick={handleCopy}
            style={{ marginTop: 12 }}
          >
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </button>
        </div>
      </div>
    </div>
  )
}
